version: '3.9'

services:
  backend:
    build: .
    container_name: backend-gestion
    ports:
      - "8080:8080"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://host.docker.internal:27027/gestion-dechet
